package link.locutus.util;

public enum PagePriority {
    LOGIN,
    FETCH_SELF,
    GUILD_SETTING,
    MAIL,
    ALLIANCE_INTERACTIONS,
    UPDATE_AA_KINGDOMS,
    UPDATE_ALLIANCES,
    FETCH_NEW,
    FETCH_CHANGED,
    ALLIANCE_STRENGTH,
    FETCH_MISSING,
    FETCH_DELETED,
    UPDATE_LEADERBOARD_KINGDOMS,
    DEFAULT,



    ;
}
